version: 2
updates:
  # Python dependencies (uv/pip)
  - package-ecosystem: pip
    directory: /gdrive_sync # Location of pyproject.toml
    schedule:
      interval: daily
    assignees:
      - mintommm

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: / # Location of workflow files
    schedule:
      interval: daily
    assignees:
      - mintommm
