# https://developers.cloudflare.com/pages/platform/known-issues/#delete-a-project-with-a-high-number-of-deployments
# https://github.com/cloudflare/cloudflare-docs/blob/production/src/content/docs/pages/platform/known-issues.mdx

name: Cleanup Old Cloudflare Deployments

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
    inputs:
      delete_aliased_deployments:
        description: 'エイリアスされたデプロイも削除しますか？ (true/false)'
        required: false
        default: false
        type: boolean

jobs:
  cleanup_deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Cloudflare Pages の古いデプロイメントをクリーンアップするスクリプトを実行
      - name: Run Cloudflare deployment cleanup script
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_PAGES_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          # 手動実行時に入力がtrueの場合のみ 'true'、それ以外は 'false' を設定
          # この複雑な式は >- (literal block scalar) を使うことで可読性を保つ
          CF_DELETE_ALIASED_DEPLOYMENTS: >-
            ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.delete_aliased_deployments == 'true') && 'true' || 'false' }}
        run: |
          echo "CF_DELETE_ALIASED_DEPLOYMENTS is set to: ${{ env.CF_DELETE_ALIASED_DEPLOYMENTS }}"
          echo "Starting Cloudflare deployment cleanup..."
          echo "Downloading the Cloudflare deployment deletion tool..."
          curl -L -o delete-all-deployments.zip https://pub-505c82ba1c844ba788b97b1ed9415e75.r2.dev/delete-all-deployments.zip

          echo "Extracting the tool..."
          unzip delete-all-deployments.zip -d ./cf-deployment-deleter

          echo "Navigating to the tool directory..."
          cd ./cf-deployment-deleter/delete-all-deployments

          echo "Installing dependencies..."
          npm install

          echo "Running the deployment deletion script..."
          npm start
